### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por ID
GET http://localhost:1234/movies/ae13b740-df71-11f0-8694-581122bb7062
### Recuperar todas las peliculas de un genero
GET http://localhost:1234/movies?genre=drama

### Crear una nueva pelicula con POST

POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Redemption",
    "year": 1994,
    "director": "Frank Darabont",
    "duration": 142,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": [
      "Drama"
    ],
    "rate": 9.3.
}



### Borrar una pelicula
DELETE http://localhost:1234/movies/671f132e-deb7-11f0-b07f-581122bb7062

### Actualizar una pelicula con PUT
PATCH http://localhost:1234/movies/671f132e-deb7-11f0-b07f-581122bb7062
Content-Type: application/json

{
  "title": "The Godfather Updated",
  "year": 2001
}