### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por ID
GET http://localhost:1234/movies/241bf55d-b649-4109-af7c-0e6890ded3fc

### Recuperar todas las peliculas de un genero
GET http://localhost:1234/movies?genre=drama

### Crear una nueva pelicula con POST

POST http://localhost:1234/movies
Content-Type: application/json

{
    "id": "dcdd0fad-a94c-4810-8acc-5f108d3b18c3",
    "title": "The Redemption",
    "year": 1994,
    "director": "Frank Darabont",
    "duration": 142,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": [
      "Drama"
    ],
    "rate": 9.3
}



### Borrar una pelicula
DELETE http://localhost:1234/movies/ad183b76-fd36-4234-b573-ed7e5f7c5db6

### Actualizar una pelicula 

PATCH http://localhost:1234/movies/241bf55d-b649-4109-af7c-0e6890ded3fc
Content-Type: application/json

{
  "title": "The Godfather Updated",
  "year": 1993
}